version: "3"
services:
  backend:
    build: ./backend
    container_name: "backend"
    command: sh -c 'python app.py'
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend
    container_name: "frontend"
    command: sh -c 'npm install; npm start'
    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/frontend

    depends_on:
      - "backend"
    stdin_open: true

    tty: true
